return {
  {
    "mason-org/mason.nvim",
    lazy = true,
    config = function()
      require("mason").setup({
        registries = {
          "github:mason-org/mason-registry",
          "github:Crashdummyy/mason-registry",
        },
      })
    end,
    opts = {
      omnisharp = { enabled = false },
      ensure_installed = {
        "astro-language-server",
        "biome",
        "cspell-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "fsautocomplete",
        "gopls",
        "json-lsp",
        "lua-language-server",
        "marksman",
        --"omnisharp",
        "pyright",
        "roslyn",
        "svelte-language-server",
        "tailwindcss-language-server",
        "vtsls",
        "vue-language-server",
        "yaml-language-server",
        "biome",
        "csharpier",
        "fantomas",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "hadolint",
        "markdown-toc",
        "markdownlint-cli2",
        "prettier",
        "ruff",
        "shfmt",
        "sqlfluff",
        "stylua",
        "tree-sitter-cli",
        "codelldb",
        "debugpy",
        "jdtls",
        "netcoredbg",
      },
    },
  },
}
