return {
  "mason-org/mason.nvim",
  dependencies = "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      "biome",
      "cspell-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "fsautocomplete",
      "gopls",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "pyright",
      "roslyn",
      "svelte-language-server",
      "tailwindcss-language-server",
      "vtsls",
      "vue-language-server",
      "yaml-language-server",
      "csharpier",
      "fantomas",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "hadolint",
      "markdown-toc",
      "markdownlint-cli2",
      "prettier",
      "ruff",
      "shfmt",
      "sqlfluff",
      "stylua",
      "tree-sitter-cli",
      "codelldb",
      "debugpy",
      "jdtls",
      "netcoredbg",
    },
  },
}
